backend:
  name: github
  repo: manarm/personal-site-gatsby
  branch: main
media_folder: static/assets
public_folder: /assets

collections:
  - name: tech
    label: tech
    folder: tech
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: url }
      - { name: github }
      - { name: body, label: Body, widget: markdown } 
  - name: art
    label: art
    folder: art
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown } 